categoriesConvention = {
    "Gaming": [
        "Rewards",
        "Board Game",
        "Leaderboard",
        "Competitive",
        "Location-based Game",
        "RPG Game",
        "Storytelling game",
        "Leveling",
        "MCQ Game",
        "Spelling Game",
        "Hints",
        "Match game",
        "Physical Iteration",
        "Kahoot!",
        "Missions game",
        "Children games",
        "Open World",
        "Help Section",
        "Mingoville",
        "Replayability",
        "Fill in the blank game",
        "Time-limited",
        "QuesTInSitu",
        "Challenge",
        "Adventure game",
        "Allow mistakes",
        "Time-free",
        "AURASMA",
        "Introductory level",
        "Use open content",
        "Notifications",
        "Quizlet",
        "Native language interface"
    ],
    "Educational": [
        "Feedback",
        "Vocabulary Acquisition",
        "Collaborative",
        "Blended Learning",
        "Visual Guide",
        "Listening acquisition",
        "Sound Guide",
        "ARCS",
        "Clear goals",
        "Communication",
        "Speaking acquisition",
        "Grammar Acquisition",
        "Problem Solving Oriented",
        "Reading acquisition",
        "Memory stimulation",
        "Learner centered",
        "Observational Learning",
        "Self-learning"
    ],
    "Technological": [
        "User Profiling",
        "Location aware",
        "Usability",
        "Social Networks Integration",
        "Speech Recognition",
        "Augmented Reality",
        "Accessibility",
        "Web-oriented",
        "Video Capture",
        "Chat",
        "Interactive Whiteboard",
        "Adaptability",
        "WLAN",
        "Hypermedia",
        "Non internet",
        "Additional device to jump"
    ]
}