categories = {
    "Accessibility": [
        "Access",
        "Access instructional Material",
        "Online game",
        "Online games"
    ],
    "Adaptability": ["Adaptability"],
    "Additional device to jump": ["Additional device to jump"],
    "Adventure game": ["Adventure game", "Robot Worlds"],
    "Allow mistakes": [
        "Allow mistakes",
        "Freedom to fail"
    ],
    "ARCS": [
        "ARCS",
        "ARCS (Attention, Relevance, Confidence, Satisfaction)"
    ],
    "Augmented Reality": [
        "AR",
        "Augmented reality",
        "QR Codes",
        "Real world objects"
    ],
    "AURASMA": ["AURASMA"],
    "Blended Learning": [
        "Flipped classroom",
        "Mixed approach",
        "Mixed environment (Real/Virtual)",
        "Simulate real scenarios",
        "Simulated scenario",
        "Virtual goods",
        "Virtual reality",
        "Virtual worlds"
    ],
    "Board Game": [
        "Based on a board game called Mahjong",
        "Block elimination game",
        "Block-clearing game",
        "Blocks building",
        "Board",
        "Board game",
        "Cards game",
        "Clickers",
        "Dungeons",
        "PUZZLE BOARD METAPHOR",
        "Puzzle",
        "Puzzles",
        "Slots",
        "Words building"
    ],
    "Challenge": ["Challenge"],
    "Chat": ["Chats records"],
    "Children games": [
        "Children games",
        "Farm game",
        "kids"
    ],
    "Clear goals": [
        "Clear goals",
        "clear goals"
    ],
    "Collaborative": [
        "Collaboration",
        "Collaborative",
        "Cooperative",
        "Cooperative learning",
        "EGameFlow",
        "Peer collaboration",
        "Peer interaction",
        "Team work",
        "Teams"
    ],
    "Communication": [
        "Communication",
        "Info sharing",
        "Multiplayer mode",
        "Peer communication",
        "communicative competence"
    ],
    "Competitive": [
        "Battles",
        "Combat",
        "Competence",
        "Competition",
        "Competition with partners",
        "Competitive",
        "Competitive learning",
        "question and answer competition"
    ],
    "Feedback": [
        "Feedback",
        "Feedback strategy",
        "Gently correction",
        "Peer feedback",
        "Positive statements",
        "Reinforcement",
        "Repetition until correct",
        "Self-evaluating",
        "feedback",
        "receptive-activation cycles"
    ],
    "Fill in the blank game": ["Fill in the blank"],
    "Grammar Acquisition": ["Grammar"],
    "Help Section": [
        "Q&A",
        "Q&A in English"
    ],
    "Hints": [],
    "Hypermedia": [],
    "Interactive Whiteboard": [],
    "Introductory level": [],
    "Kahoot!": [],
    "Kinect": [],
    "Leaderboard": [],
    "Learner centered": [],
    "Leveling": [],
    "Listening acquisition": [],
    "Location aware": [],
    "Location-based Game": [],
    "Match game": [],
    "MCQ Game": [],
    "Memory stimulation": [],
    "Mingoville": [],
    "Missions game": [],
    "Native language interface": [],
    "No clearly described": [],
    "Non internet": [],
    "Notifications": [],
    "Observational Learning": [],
    "Open World": [],
    "Physical Iteration": [],
    "Problem Solving Oriented": [],
    "QuesTInSitu": [],
    "Quizlet": [],
    "Reading acquisition": [],
    "Replayability": [],
    "RETAIN model": [],
    "Rewards": [],
    "RPG Game": [],
    "Social Networks Integration": [],
    "Sound Guide": [],
    "Speaking acquisition": [],
    "Speech Recognition": [],
    "Spelling Game": [],
    "Storytelling game": [],
    "Time-free": [],
    "Time-limited": [],
    "Usability": [],
    "Use open content": [],
    "User Profiling": [],
    "Video Capture": [],
    "Video Guide": [],
    "Visual Guide": [],
    "Vocabulary Acquisition": [],
    "Web-oriented": [],
    "WLAN": []
}
